spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZouHongxue/config-repo
          search-paths: config
      label: main
server:
  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8750/eureka/, http://peer2:8751/eureka/